-- CreateEnum
CREATE TYPE "MapStyle" AS ENUM ('SATELLITE', 'SATELLITE_STREETS', 'OUTDOORS', 'STREETS', 'LIGHT', 'DARK');

-- AlterTable
ALTER TABLE "Dropzone" ADD COLUMN     "mapStyle" "MapStyle" NOT NULL DEFAULT 'SATELLITE_STREETS';
